In [2]:
import copy
a=[10,12,14,[1,2]]
b=a
c=a.copy()
d=copy.deepcopy(a)
e=copy.copy(a)
b[3][1]=20
print(a)

[10, 12, 14, [1, 20]]


In [3]:
print(b)

[10, 12, 14, [1, 20]]


In [4]:
print(c)

[10, 12, 14, [1, 20]]


In [5]:
print(d)

[10, 12, 14, [1, 2]]


In [6]:
print(e)

[10, 12, 14, [1, 20]]


In [19]:
import numpy as np
aa=np.array([[[1,2,3],[13,20,34]],[[3,4,5],[37,43,52]]])
aa[1,1]

array([37, 43, 52])

In [20]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [21]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [23]:
np.random.seed(10)
np.random.randint( 6, 10, (8,6) )

array([[7, 7, 6, 9, 6, 7],
       [9, 6, 7, 7, 6, 7],
       [7, 8, 6, 7, 6, 8],
       [6, 8, 6, 9, 6, 6],
       [9, 9, 8, 6, 9, 8],
       [8, 7, 6, 6, 8, 7],
       [9, 8, 7, 7, 7, 9],
       [7, 8, 7, 6, 8, 8]])

In [31]:
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [32]:
a=[2,3,4,5]
b=[26,8]
a+b

[2, 3, 4, 5, 26, 8]

In [35]:
import pandas as pd
s1=pd.Series([0,2,4,6,8,10,12])
s2=pd.Series([0,3,6,9,12,15])
s1[s1.isin(s2)].index=s2[s2.isin(s1)].index

In [36]:
first = {"Teams":[["chelesa",38,30],["To",38,26],["FE",48,16]]}

In [37]:
first

{'Teams': [['chelesa', 38, 30], ['To', 38, 26], ['FE', 48, 16]]}

In [ ]:
a1=pd.