In [3]:
import numpy as np
a = np.array([11, 12, 13, 14])
b = np.array([1, 2, 3, 4])
c = a - b
c

array([10, 10, 10, 10])

In [4]:
a = 9/2
a

4.5

In [5]:
b = 5.2/2
b

2.6

In [8]:
import pandas as pd
series = pd.Series(3,index=['a','b','c'])
series

a    3
b    3
c    3
dtype: int64

In [11]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.linspace(5,15,10)

array([ 5.        ,  6.11111111,  7.22222222,  8.33333333,  9.44444444,
       10.55555556, 11.66666667, 12.77777778, 13.88888889, 15.        ])

In [16]:
5.0+.10

5.1

In [17]:
print(type(5 // 2))

<class 'int'>


In [19]:
np.nan(2)

TypeError: 'float' object is not callable

In [20]:
Which of the following functions is used to manage missing data

SyntaxError: invalid syntax (1604065117.py, line 1)

In [21]:
A = np.array([1, 2, 3])

In [22]:
B = np.vsplit(A, len(A))

ValueError: vsplit only works on arrays of 2 or more dimensions

In [25]:
list1 = [1, 2, 3]
list2 = ['a', 'b', 'c']

# Pair the elements using zip()
paired_list = list(zip(list1, list2))

print(paired_list)

[(1, 'a'), (2, 'b'), (3, 'c')]


In [27]:
import numpy as np

# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Flatten the 2D array using ravel()
flattened_arr = arr_2d.ravel()

print(arr_2d)
# Output:
# [[1 2 3]
#  [4 5 6]]

print(flattened_arr)
# Output: [1 2 3 4 5 6]

# Check the number of dimensions of both arrays
print(arr_2d.shape)
# Output: 2

print(flattened_arr.ndim)
# Output: 1


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
(2, 3)
1


In [33]:
a1 = [1, 3]
b1 = a1
a1[0] = 4
print(b1)

[4, 3]


In [39]:
import pandas as pd

# Example Series
data = pd.Series([1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5])

# Get the count of unique values
value_counts = data.value_counts()

value_counts

4    4
3    3
2    2
5    2
1    1
dtype: int64

In [36]:
min(max(False,-3,-4), 2,7)

False

In [37]:
max(False,-3,-4)

False

In [38]:
len(["hi",6, 9, 5])

4